VERSION 0.8

prepare-build-deps:
    FROM earthly/dind:ubuntu-24.04-docker-27.3.1-1
    RUN apt-get update && \
        apt-get install -y curl build-essential libssl-dev pkg-config && \
        curl https://sh.rustup.rs -sSf | bash -s -- -y && \
        /bin/bash -c "source $HOME/.cargo/env && cargo install cargo-nextest --locked"

copy-src-and-prepare-build-deps:
    FROM +prepare-build-deps
    WORKDIR /docker-app
    COPY ./.cargo ./.cargo
    COPY Cargo.lock Cargo.toml ./
    COPY --dir ./src ./migration ./

# Common deps for performing various types of tests
tests-base:
    FROM +copy-src-and-prepare-build-deps
    RUN /bin/bash -c "source $HOME/.cargo/env && cargo +stable install cargo-llvm-cov --locked" && \
        apt install postgresql-client -y
    COPY ./tests/tests-compose.yaml ./tests/setup_db_urls.sh ./tests/coverage.sh ./

integration-test-with-coverage:
    FROM +tests-base
    WITH DOCKER --compose ./tests-compose.yaml
        RUN --no-cache while ! pg_isready --host=localhost --port=5432 --dbname=t0 --username=postgres; do sleep 1; done ; \
            /bin/bash -c "source $HOME/.cargo/env &&
                source ./setup_db_urls.sh &&
                ./coverage.sh
            ";
    END
    SAVE ARTIFACT ./lcov.info AS LOCAL ./lcov.info